jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/jwt_security
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true